import React from 'react'
import Head from 'next/head'
import Header from '../Header'


type Props = {
  title: string
  children: React.ReactNode
}

const MasterClass = ({ title, children }: Props) => {
  return (
    <>
      {/* <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={true} />
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet" />
      </Head> */}

      <Header />

      {children}
    </>
  )
}

export default MasterClass
